from __future__ import annotations

import json
from itertools import count
import re
from urllib import error, request

from app.infrastructure.llm.json_content import parse_json_content
from app.simulation.planner import AbstractStoryPlanner
from app.simulation.protocol import CapabilitySpec, StoryPlan, StoryStep


class SiliconFlowStoryPlanner(AbstractStoryPlanner):
    def __init__(
        self,
        *,
        api_key: str,
        model_name: str,
        base_url: str,
        max_attempts: int = 3,
    ) -> None:
        self.api_key = api_key
        self.model_name = model_name
        self.base_url = base_url.rstrip("/")
        self.max_attempts = max(1, max_attempts)
        self._story_counter = count(1)

    def build_story_plan(
        self,
        *,
        goal: str,
        actors: list[str],
        capabilities: list[CapabilitySpec],
    ) -> StoryPlan:
        payload = self._build_payload(goal=goal, actors=actors, capabilities=capabilities)
        capability_names = {item.name for item in capabilities}
        parsed: dict | None = None
        last_error = "unknown error"
        needs_strict_reference_fix = False
        for _attempt in range(1, self.max_attempts + 1):
            if needs_strict_reference_fix:
                payload["messages"].append(
                    {
                        "role": "user",
                        "content": (
                            "Your previous JSON used invalid or fragile references. "
                            "Rewrite with concrete executable references only, such as '$step_1.output.threads[0].id'. "
                            "Never use '[?]', '<index>', 'latest', or references that depend on possibly empty arrays. "
                            "For forum publishing goals, avoid read_thread steps unless the thread ID is guaranteed from a previous create_thread step."
                        ),
                    }
                )

            parsed, error_reason = self._call_model(payload)
            if parsed is None:
                last_error = error_reason or "invalid or empty planner response"
                continue

            if self._has_invalid_references(parsed):
                needs_strict_reference_fix = True
                last_error = "planner returned invalid reference placeholders"
                continue

            steps = self._build_steps(parsed, actors)
            if not steps:
                last_error = "planner returned no usable steps"
                continue

            steps = self._enforce_story_chain(
                steps=steps,
                actors=actors,
                capabilities=capability_names,
                goal=goal,
            )

            if self._steps_have_invalid_references(steps):
                needs_strict_reference_fix = True
                last_error = "planner steps still contain invalid references"
                continue

            if self._steps_are_fragile(steps):
                needs_strict_reference_fix = True
                last_error = "planner returned fragile references (possibly empty board thread list)"
                continue

            story_id = str(parsed.get("story_id", f"sf-story-{next(self._story_counter):04d}"))
            return StoryPlan(
                story_id=story_id,
                goal=goal,
                steps=steps,
                planner_name="siliconflow",
                planner_source=f"remote_llm:{self.model_name}",
                fallback_used=False,
                planner_detail="Plan generated by SiliconFlow remote planner with enforced discovery-investigation-outcome chain.",
            )

        raise RuntimeError(
            f"SiliconFlow planner failed after {self.max_attempts} attempts: {last_error}"
        )

    def _build_steps(self, parsed: dict, actors: list[str]) -> list[StoryStep]:
        steps_data = parsed.get("steps", [])
        steps: list[StoryStep] = []
        for index, item in enumerate(steps_data, start=1):
            capability = str(item.get("capability", "")).strip()
            actor_id = str(item.get("actor_id", actors[0] if actors else "aria")).strip()
            payload_data = item.get("payload", {})
            depends_on = item.get("depends_on", [])
            rationale = str(item.get("rationale", "")).strip()
            if not capability or not isinstance(payload_data, dict):
                continue
            if not isinstance(depends_on, list):
                depends_on = []
            steps.append(
                StoryStep(
                    step_id=str(item.get("step_id", f"step-{index}")),
                    capability=capability,
                    actor_id=actor_id,
                    payload=payload_data,
                    depends_on=[str(dep) for dep in depends_on],
                    rationale=rationale,
                )
            )
        return steps

    def _build_payload(self, *, goal: str, actors: list[str], capabilities: list[CapabilitySpec]) -> dict:
        capability_lines = []
        for item in capabilities:
            capability_lines.append(
                {
                    "name": item.name,
                    "site": item.site,
                    "description": item.description,
                    "read_only": item.read_only,
                    "input_schema": item.input_schema,
                }
            )

        system_prompt = (
            "You are a story planner for a multi-site AI society simulation. "
            "Return ONLY JSON with fields: story_id, steps[]. "
            "Each step must include: step_id, capability, actor_id, payload, depends_on, rationale. "
            "Only use provided capabilities. Ensure causality and cross-site consistency. "
            "Build a complete chain with three phases: discovery -> investigation -> outcome. "
            "Investigation should include discussion by other actors via forum.reply_thread when available. "
            "Outcome should be published by a different actor, preferably in news.publish_article or a second forum thread. "
            "If an input_schema includes allowed_* values, you MUST use one of those exact values. "
            "Do not invent board slugs, thread ids, site ids, or capability names. "
            "When a later step needs an object from an earlier step, reference it explicitly using '$step_id.output.field' syntax. "
            "Example: use '$step_1.output.threads[0].id' or '$step_2.output.thread_id' instead of invented placeholders. "
            "Decide whether to include image generation based on goal intent. "
            "If image generation is included, add exactly one 'image.generate' step and pass '$<image_step>.output.image_url' to publishable steps. "
            "For publishable text fields such as title/content, always use English text. "
            "For any publishable text such as title/content, write the final in-world forum text directly. "
            "If the goal implies website/page generation and main.generate_page is available, include a main.generate_page step. "
            "When main.read_page is available and a page was generated, include a readback step that references '$<generate_step>.output.slug'. "
            "Do not include prompt language like '生成一个', '请生成', '你是', '输出JSON', or any meta instructions in the content fields."
        )

        user_prompt = {
            "goal": goal,
            "actors": actors,
            "capabilities": capability_lines,
        }

        return {
            "model": self.model_name,
            "temperature": 0.2,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": json.dumps(user_prompt, ensure_ascii=True)},
            ],
            "response_format": {"type": "json_object"},
        }

    def _call_model(self, payload: dict) -> tuple[dict | None, str | None]:
        endpoint = f"{self.base_url}/chat/completions"
        body = json.dumps(payload).encode("utf-8")
        http_request = request.Request(
            endpoint,
            data=body,
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )

        try:
            with request.urlopen(http_request, timeout=60) as response:
                response_text = response.read().decode("utf-8")
        except TimeoutError:
            return None, "timeout"
        except error.HTTPError as exc:
            try:
                body_preview = exc.read().decode("utf-8", errors="replace")[:400]
            except Exception:
                body_preview = "<unavailable>"
            return None, f"http {exc.code}: {body_preview}"
        except error.URLError as exc:
            return None, f"url_error: {exc.reason}"

        try:
            data = json.loads(response_text)
            content = data["choices"][0]["message"]["content"]
            parsed = parse_json_content(content)
            if parsed is None:
                return None, "content_json_parse_failed"
            return parsed, None
        except (KeyError, IndexError, TypeError, ValueError, json.JSONDecodeError) as exc:
            return None, f"response_parse_error: {exc}"

    def _has_invalid_references(self, parsed: dict) -> bool:
        steps = parsed.get("steps", [])
        if not isinstance(steps, list):
            return True
        for item in steps:
            payload = item.get("payload", {}) if isinstance(item, dict) else {}
            if self._payload_has_invalid_reference(payload):
                return True
        return False

    def _steps_have_invalid_references(self, steps: list[StoryStep]) -> bool:
        return any(self._payload_has_invalid_reference(step.payload) for step in steps)

    def _steps_are_fragile(self, steps: list[StoryStep]) -> bool:
        step_capabilities = {step.step_id: step.capability for step in steps}

        def uses_board_thread_reference(payload: dict) -> bool:
            for value in payload.values():
                if isinstance(value, dict) and uses_board_thread_reference(value):
                    return True
                if isinstance(value, list):
                    if any(isinstance(item, dict) and uses_board_thread_reference(item) for item in value):
                        return True
                    if any(isinstance(item, str) and self._is_board_thread_reference(item, step_capabilities) for item in value):
                        return True
                if isinstance(value, str) and self._is_board_thread_reference(value, step_capabilities):
                    return True
            return False

        return any(uses_board_thread_reference(step.payload) for step in steps)

    def _is_board_thread_reference(self, value: str, step_capabilities: dict[str, str]) -> bool:
        match = re.search(r"\$?(step[_-]\d+)\.output\.threads\[(\d+)\]\.id", value)
        if not match:
            return False
        referenced_step = match.group(1)
        return step_capabilities.get(referenced_step) == "forum.read_board"

    def _payload_has_invalid_reference(self, payload: dict) -> bool:
        placeholder_patterns = [
            re.compile(r"\[\?\]"),
            re.compile(r"<index>", re.IGNORECASE),
            re.compile(r"\$step[_-]\d+\.output\.[^\s]*latest", re.IGNORECASE),
        ]

        def contains_invalid(value) -> bool:
            if isinstance(value, dict):
                return any(contains_invalid(item) for item in value.values())
            if isinstance(value, list):
                return any(contains_invalid(item) for item in value)
            if not isinstance(value, str):
                return False
            return any(pattern.search(value) for pattern in placeholder_patterns)

        return contains_invalid(payload)

    def _enforce_story_chain(
        self,
        *,
        steps: list[StoryStep],
        actors: list[str],
        capabilities: set[str],
        goal: str,
    ) -> list[StoryStep]:
        if not actors:
            actors = ["aria"]

        should_generate_image = self._should_enable_image_generation(
            goal=goal,
            default=("forum.create_thread" in capabilities or "social.create_post" in capabilities),
        )

        chain_steps = list(steps)
        actor_cycle = list(actors)

        def actor_for(offset: int) -> str:
            return actor_cycle[offset % len(actor_cycle)]

        def find_first(capability: str) -> StoryStep | None:
            for item in chain_steps:
                if item.capability == capability:
                    return item
            return None

        def find_all(capability: str) -> list[StoryStep]:
            return [item for item in chain_steps if item.capability == capability]

        def next_step_id() -> str:
            existing = {item.step_id for item in chain_steps}
            index = 1
            while True:
                candidate = f"step-auto-{index}"
                if candidate not in existing:
                    return candidate
                index += 1

        def append_step(
            *,
            capability: str,
            actor_id: str,
            payload: dict,
            depends_on: list[str],
            rationale: str,
        ) -> StoryStep:
            step = StoryStep(
                step_id=next_step_id(),
                capability=capability,
                actor_id=actor_id,
                payload=payload,
                depends_on=depends_on,
                rationale=rationale,
            )
            chain_steps.append(step)
            return step

        share_step = find_first("netdisk.create_share_link")
        thread_step = find_first("forum.create_thread")

        if thread_step is None and "forum.create_thread" in capabilities:
            upload_step: StoryStep | None = None
            if "netdisk.upload_file" in capabilities:
                upload_step = append_step(
                    capability="netdisk.upload_file",
                    actor_id=actor_for(0),
                    payload={
                        "title": "Initial Observation Log",
                        "purpose": f"Capture first-stage evidence for: {goal.strip() or 'suspicious event'}",
                        "file_name": "initial_observation_log.txt",
                    },
                    depends_on=[],
                    rationale="Discovery phase: create a traceable evidence file.",
                )
            if share_step is None and upload_step is not None and "netdisk.create_share_link" in capabilities:
                share_step = append_step(
                    capability="netdisk.create_share_link",
                    actor_id=actor_for(0),
                    payload={
                        "resource_id": f"${upload_step.step_id}.output.resource_id",
                    },
                    depends_on=[upload_step.step_id],
                    rationale="Discovery phase: create a shareable evidence link.",
                )
            thread_payload = {
                "board_slug": "town-square",
                "title": "[Discovery] Unusual Activity Reported",
                "content": "I noticed an unusual pattern and opened this thread for structured investigation.",
                "tags": ["discovery", "investigation", "evidence"],
            }
            thread_depends: list[str] = []
            if share_step is not None:
                thread_payload["netdisk_share_id"] = f"${share_step.step_id}.output.share_id"
                thread_payload["netdisk_access_code"] = f"${share_step.step_id}.output.access_code"
                thread_depends = [share_step.step_id]
            elif upload_step is not None:
                thread_depends = [upload_step.step_id]

            thread_step = append_step(
                capability="forum.create_thread",
                actor_id=actor_for(0),
                payload=thread_payload,
                depends_on=thread_depends,
                rationale="Discovery phase: open the initial thread for public discussion.",
            )

        reply_steps = find_all("forum.reply_thread")
        if thread_step is not None and "forum.reply_thread" in capabilities:
            target_reply_count = 2 if len(actor_cycle) >= 3 else 1
            while len(reply_steps) < target_reply_count:
                reply_actor = actor_for(len(reply_steps) + 1)
                reply = append_step(
                    capability="forum.reply_thread",
                    actor_id=reply_actor,
                    payload={
                        "thread_id": f"${thread_step.step_id}.output.thread_id",
                        "content": "Adding follow-up observations and challenging assumptions from earlier comments.",
                    },
                    depends_on=[thread_step.step_id],
                    rationale="Investigation phase: gather multi-actor viewpoints in the same thread.",
                )
                reply_steps.append(reply)

        has_outcome_news = any(item.capability == "news.publish_article" for item in chain_steps)
        outcome_thread_count = sum(1 for item in chain_steps if item.capability == "forum.create_thread")
        generated_page_steps = [item for item in chain_steps if item.capability == "main.generate_page"]
        has_read_page_step = any(item.capability == "main.read_page" for item in chain_steps)

        web_goal = self._goal_implies_webpage(goal)
        if web_goal and not generated_page_steps and "main.generate_page" in capabilities:
            depends = []
            if chain_steps:
                depends = [chain_steps[-1].step_id]
            generated_page_steps.append(
                append_step(
                    capability="main.generate_page",
                    actor_id=actor_for(0),
                    payload={
                        "title": "Official Case Update Page",
                        "description": "Publish a concise investigation landing page for public reading.",
                        "slug": "case-update",
                        "style": "investigation_portal",
                    },
                    depends_on=depends,
                    rationale="Outcome phase: generate a dedicated webpage for public-facing story context.",
                )
            )

        if generated_page_steps and "main.read_page" in capabilities and not has_read_page_step:
            page_step = generated_page_steps[-1]
            append_step(
                capability="main.read_page",
                actor_id=actor_for(1),
                payload={
                    "slug": f"${page_step.step_id}.output.slug",
                },
                depends_on=[page_step.step_id],
                rationale="Readback phase: verify the published webpage is retrievable when later steps need it.",
            )

        if generated_page_steps:
            page_step = generated_page_steps[-1]
            slug_ref = f"${page_step.step_id}.output.slug"
            for step in chain_steps:
                if step.capability != "main.read_page":
                    continue
                step.payload["slug"] = slug_ref
                if page_step.step_id not in step.depends_on:
                    step.depends_on.append(page_step.step_id)

        if not has_outcome_news and "news.publish_article" in capabilities and thread_step is not None:
            depends = [thread_step.step_id] + [item.step_id for item in reply_steps]
            if share_step is not None:
                depends.append(share_step.step_id)
            news_payload = {
                "title": "Investigation Update: Findings Compiled",
                "content": "This report consolidates the discovery thread, follow-up discussion, and current conclusion.",
                "category": "investigation",
                "is_pinned": False,
                "related_thread_ids": [f"${thread_step.step_id}.output.thread_id"],
                "related_share_ids": [f"${share_step.step_id}.output.share_id"] if share_step is not None else [],
            }
            append_step(
                capability="news.publish_article",
                actor_id=actor_for(2),
                payload=news_payload,
                depends_on=depends,
                rationale="Outcome phase: publish the cross-site investigation result in news.",
            )

        if outcome_thread_count < 2 and "forum.create_thread" in capabilities and thread_step is not None:
            depends = [thread_step.step_id] + [item.step_id for item in reply_steps]
            summary_payload = {
                "board_slug": "town-square",
                "title": "[Result] Investigation Summary and Next Steps",
                "content": "Based on the prior thread and discussion, this is the consolidated conclusion and next action plan.",
                "tags": ["result", "summary", "follow-up"],
            }
            if share_step is not None:
                summary_payload["netdisk_share_id"] = f"${share_step.step_id}.output.share_id"
                summary_payload["netdisk_access_code"] = f"${share_step.step_id}.output.access_code"
                depends.append(share_step.step_id)
            append_step(
                capability="forum.create_thread",
                actor_id=actor_for(1),
                payload=summary_payload,
                depends_on=depends,
                rationale="Outcome phase: publish a separate summary thread by another actor.",
            )

        chain_steps = self._apply_image_policy(
            steps=chain_steps,
            capabilities=capabilities,
            should_generate_image=should_generate_image,
            actor_id=actor_for(0),
        )

        return chain_steps

    def _apply_image_policy(
        self,
        *,
        steps: list[StoryStep],
        capabilities: set[str],
        should_generate_image: bool,
        actor_id: str,
    ) -> list[StoryStep]:
        if "image.generate" not in capabilities:
            for step in steps:
                step.payload.pop("image_url", None)
            return self._cleanup_missing_dependencies(steps)

        if not should_generate_image:
            filtered = [step for step in steps if step.capability != "image.generate"]
            for step in filtered:
                step.payload.pop("image_url", None)
            return self._cleanup_missing_dependencies(filtered)

        image_step = next((step for step in steps if step.capability == "image.generate"), None)
        if image_step is None:
            image_step = StoryStep(
                step_id=self._next_auto_step_id(steps),
                capability="image.generate",
                actor_id=actor_id,
                payload={
                    "prompt": "Evidence-style image for the current story thread",
                    "width": 512,
                    "height": 512,
                },
                depends_on=[],
                rationale="Generate one visual asset for the publishing phase.",
            )
            insertion_index = self._find_first_publish_index(steps)
            if insertion_index < 0:
                steps.append(image_step)
            else:
                steps.insert(insertion_index, image_step)

        image_ref = f"${image_step.step_id}.output.image_url"
        for step in steps:
            if step.capability in {"forum.create_thread", "social.create_post"}:
                if not str(step.payload.get("image_url", "")).strip():
                    step.payload["image_url"] = image_ref
                if image_step.step_id not in step.depends_on:
                    step.depends_on.append(image_step.step_id)

        return self._cleanup_missing_dependencies(steps)

    @staticmethod
    def _find_first_publish_index(steps: list[StoryStep]) -> int:
        for index, step in enumerate(steps):
            if step.capability in {"forum.create_thread", "social.create_post", "news.publish_article"}:
                return index
        return -1

    @staticmethod
    def _next_auto_step_id(steps: list[StoryStep]) -> str:
        existing = {step.step_id for step in steps}
        index = 1
        while True:
            candidate = f"step-auto-image-{index}"
            if candidate not in existing:
                return candidate
            index += 1

    @staticmethod
    def _cleanup_missing_dependencies(steps: list[StoryStep]) -> list[StoryStep]:
        step_ids = {step.step_id for step in steps}
        for step in steps:
            step.depends_on = [dependency for dependency in step.depends_on if dependency in step_ids]
        return steps

    @staticmethod
    def _should_enable_image_generation(*, goal: str, default: bool) -> bool:
        normalized = re.sub(r"\s+", " ", goal.strip().lower())
        if not normalized:
            return default

        disabled_keywords = (
            "no image",
            "without image",
            "text only",
            "plain text",
            "不需要图片",
            "不要图片",
            "无需图片",
            "纯文字",
        )
        if any(keyword in normalized for keyword in disabled_keywords):
            return False

        enabled_keywords = (
            "image",
            "picture",
            "photo",
            "illustration",
            "poster",
            "封面",
            "插图",
            "图片",
            "配图",
        )
        if any(keyword in normalized for keyword in enabled_keywords):
            return True

        return default

    @staticmethod
    def _goal_implies_webpage(goal: str) -> bool:
        normalized = goal.strip().lower()
        if not normalized:
            return False
        keywords = (
            "web",
            "website",
            "webpage",
            "home page",
            "homepage",
            "landing page",
            "company page",
            "profile page",
            "门户",
            "网页",
            "页面",
            "官网",
            "主页",
            "公司页",
            "个人页",
        )
        return any(token in normalized for token in keywords)
